### ISSUE TITLE
NvChad doesn't work

### ISSUE THREAD

**Issue by TimofeyAxenov** [nix-community/nix4nvchad#52]
When I attempt to launch NvChad, I get this error:

Error detected while processing /home/timofey/.config/nvim/init.lua:

E5113: Error while calling lua chunk: /home/timofey/.config/nvim/lua
/init.lua:7: attempt to index field 'uv' (a nil value)
stack traceback:
        /home/timofey/.config/nvim/lua/init.lua:7: in main chunk
        [C]: in function 'require'
        /home/timofey/.config/nvim/init.lua:1: in main chunk

Everything is installed just like in the guide. I tried doing what was in #6, no help

sudo nvim also doesn't launch the program, it gives this error:
rror detected while processing /root/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /root/.config/nvim/lua/init.lu
a:7: attempt to index field 'uv' (a nil value)
stack traceback:
        /root/.config/nvim/lua/init.lua:7: in main chunk
        [C]: in function 'require'
        /root/.config/nvim/init.lua:1: in main chunk

**Comment by TimofeyAxenov** [comment]
I installed it in a flake

**Comment by TimofeyAxenov** [comment]
@Bot-wxt1221 I followed the installation steps from the readme that come after the nix run section. So, nvchad4nix is in inputs and follows nixpkgs. programs.nvchad is enabled in home manager which is installed separately from the system. nixpkgs={overlays=[]} is in flake configuration modules. Can't send the flake.nix rn, I'm not at my laptop and I still haven't put my latest dots on GitHub. I was pushing before, but rn the repository in my profile is way behind the system

**Comment by sven** [comment]
> @TimofeyAxenov I can't reduce your error. Maybe you use neovim 0.9. [nvim-lua/kickstart.nvim#1073](https://github.com/nvim-lua/kickstart.nvim/issues/1073)

Thank you, that was a good pointer as I had the same problem. After overlaying Neovim from Unstable the `uv`-problem was gone.
